(() => {
  'use strict';
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const categories=['Writing','Software','Business','Music','Art','Film','Personal','Research','Invention'];
  const CONTROL='https://oyoacuakzwsvxmzcckot.supabase.co/functions/v1/museum-control';
  const base=[
    {id:'A—001842',title:'The Third Version of a Novel',category:'Writing',year:'2018',status:'Unattended',visual:'paper',description:'Eleven chapters survived, along with character maps and a final sentence that was never decided',text:'Chapter twelve was going to explain the whole arrangement\n\nThe room had already been described twice, although the second description was better and the first one was still in the document because removing it felt too final\n\nAt some point the narrator was supposed to leave the house and meet the person mentioned in chapter four\n\nThere is a note in the margin that says return to this when the ending is known\n\nThe ending was never known',note:'The last recorded revision was made after midnight',username:'Anonymous'},
    {id:'A—002117',title:'A Restaurant That Was Never Opened',category:'Business',year:'2020',status:'Shelved',visual:'red',description:'A complete identity system, menu, floor plan and opening budget for a restaurant that remained on paper',text:'The menu was finished first because it was the easiest part to make look real\n\nThere were six tables, two menus, a name that everyone liked and a spreadsheet containing the exact number of plates required for opening week\n\nThe lease was discussed for three months\n\nThe final version of the floor plan has a small pencil mark beside table four which says move this if possible\n\nNothing was moved',note:'The restaurant had a name but never had a first customer',username:'Anonymous'},
    {id:'A—002904',title:'Six Songs for an Album',category:'Music',year:'2017',status:'Unresolved',visual:'blue',description:'Six recordings, four album covers and a seventh track that was repeatedly mentioned but never recorded',text:'Track one was finished on a Sunday\n\nTrack two was rewritten because the first version sounded too optimistic\n\nTrack three had a chorus that everyone liked\n\nTrack four was supposed to be shorter\n\nTrack five became a different song halfway through\n\nTrack six was recorded twice and both versions were kept\n\nThe folder contains a file called seventh song ideas which begins with',note:'No release date was ever selected',username:'Anonymous'},
    {id:'A—003186',title:'The Personal Website',category:'Personal',year:'2021',status:'Unattended',visual:'paper',description:'A personal website revised fourteen times before the domain expired',text:'The first homepage said hello\n\nThe second homepage explained too much\n\nThe third homepage was minimal\n\nThe fourth homepage was even more minimal and therefore contained almost nothing\n\nBy version fourteen the site had a typeface, a tiny archive, a page about the archive and a button that led to a page that was still being considered\n\nThe domain expired before the button was given a purpose',note:'The screenshot folder is still named website final',username:'Anonymous'},
    {id:'A—003721',title:'A Small Clothing Label',category:'Business',year:'2019',status:'Shelved',visual:'yellow',description:'Fabric samples, a name, twelve logo variations and one unusually ambitious spreadsheet',text:'The name was chosen in April\n\nBy May there were twelve logos\n\nBy June there were seven possible suppliers and a spreadsheet calculating the cost of every button\n\nThe first sample arrived in a box that was much smaller than expected\n\nThere was a meeting about production\n\nAfter the meeting a new tab called revised production costs was created\n\nThat tab is empty',note:'Production never began',username:'Anonymous'},
    {id:'A—004802',title:'A Short Film About Tuesday',category:'Film',year:'2022',status:'Unresolved',visual:'green',description:'Sixteen minutes of footage survive from a film intended to be considerably longer',text:'The opening shot was supposed to last twelve seconds\n\nIt lasted forty\n\nThe main character enters a shop, forgets why they came in and then notices a person outside who is never introduced\n\nThere was meant to be a second scene\n\nThe notes say the second scene explains everything\n\nThe footage folder ends after the first scene',note:'Sixteen minutes survive',username:'Anonymous'},
    {id:'A—005667',title:'The Board Game',category:'Invention',year:'2016',status:'Unattended',visual:'red',description:'A complete rulebook, provisional scoring system and an unresolved disagreement about dice',text:'The object of the game was to build a city without running out of time\n\nThe first version took three hours\n\nThe second version took five\n\nA note beside the third version says this is becoming a problem\n\nThere are rules for roads, markets, weather and one event called unexpected meeting\n\nThe rules for unexpected meeting are missing',note:'Rules exist. Pieces do not',username:'Anonymous'},
    {id:'A—006914',title:'The Furniture Prototype',category:'Art',year:'2021',status:'Unresolved',visual:'yellow',description:'An attempt to combine traditional joinery with a very optimistic understanding of geometry',text:'The first chair stood for approximately three weeks\n\nIt was comfortable if nobody leaned backwards\n\nThe second version was taller\n\nThe third version was supposed to solve the problem with a diagonal support\n\nA diagram shows the diagonal support\n\nThe actual support was never made\n\nThere is a note saying order longer screws',note:'One chair exists',username:'Anonymous'},
    {id:'A—007201',title:'The Language Learning System',category:'Research',year:'2019',status:'Unattended',visual:'green',description:'A personal language-learning method abandoned after a year and 1,842 recorded words',text:'The method began with ten words a day\n\nAfter two weeks the list became fifteen words\n\nAfter one month there were colour codes\n\nAfter three months there was a spreadsheet with columns for recognition, recall, pronunciation and words that were somehow remembered only while walking\n\nThe last page contains twenty new words\n\nNone of them are translated',note:'Vocabulary list: 1,842 words',username:'Anonymous'},
    {id:'A—007643',title:'The Research Paper',category:'Research',year:'2020',status:'Unresolved',visual:'dark',description:'An excellent introduction, a complete abstract and no conclusion',text:'The abstract was finished first\n\nThe introduction became the strongest part of the paper by accident\n\nThere are references to nine sources and a note to find two more\n\nThe results section contains a table followed by the sentence these findings require further analysis\n\nThe discussion begins\n\nThe discussion does not continue',note:'Abstract complete',username:'Anonymous'},
    {id:'A—008391',title:'The Photography Book',category:'Art',year:'2017',status:'Unattended',visual:'blue',description:'Forty-eight photographs from train stations arranged into a book that never reached printing',text:'The photographs were selected by location\n\nThen they were selected by colour\n\nThen the order was changed because the first photograph felt too final\n\nThe cover went through six versions\n\nThe title changed three times\n\nThe final PDF is 48 pages\n\nPage 49 is blank',note:'The photographs survived the project',username:'Anonymous'},
    {id:'A—010931',title:'The Poetry Collection',category:'Writing',year:'2020',status:'Unattended',visual:'paper',description:'Thirty-two poems arranged into four intended sections. The fourth section remains empty',text:'Section one was about leaving\n\nSection two was about returning\n\nSection three became unexpectedly long\n\nThere are notes beside several poems saying cut this later\n\nThe final page is headed SECTION FOUR\n\nUnder the heading there is a single line\n\nwrite something quieter here',note:'Thirty-two poems',username:'Anonymous'}
  ];
  let stories=[...base],filter='All',current=null,supa=null,adminToken=sessionStorage.getItem('mout-admin-token')||'';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  if(window.supabase&&window.MOUT_CONFIG?.supabaseUrl)try{supa=window.supabase.createClient(window.MOUT_CONFIG.supabaseUrl,window.MOUT_CONFIG.supabaseAnonKey)}catch{}
  const open=id=>{$(id).classList.add('open');$(id).setAttribute('aria-hidden','false');document.body.style.overflow='hidden'};
  const close=()=>{$$('.modal-backdrop').forEach(x=>{x.classList.remove('open');x.setAttribute('aria-hidden','true')});document.body.style.overflow=''};
  const toast=m=>{let t=$('#toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.append(t)}t.textContent=m;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),2200)};
  function buildFilters(){const el=$('#filters');el.innerHTML=['All',...categories].map(c=>`<button class="filter ${c===filter?'active':''}" data-filter="${esc(c)}">${esc(c)}</button>`).join('');$$('.filter').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x===b));render()})}
  function render(){const q=($('#searchInput')?.value||'').toLowerCase().trim();const shown=stories.filter(s=>(filter==='All'||s.category===filter)&&`${s.id} ${s.title} ${s.category} ${s.year} ${s.description} ${s.text} ${s.username}`.toLowerCase().includes(q));$('#artifactCount').textContent=stories.length;$('#statRecords').textContent=stories.length;$('#collectionGrid').hidden=!shown.length;$('#emptyState').hidden=!!shown.length;$('#collectionGrid').innerHTML=shown.map(s=>`<article class="artifact-card" tabindex="0" data-id="${esc(s.id)}"><div class="artifact-visual visual-${esc(s.visual)}"><span class="eyebrow">${esc(s.id)}</span><div class="visual-title">${esc(s.title)}</div></div><div class="card-meta"><div><h3 class="card-title">${esc(s.title)}</h3><div class="card-info">${esc(s.category)} / ${esc(s.year)}</div></div><span class="card-status">${esc(s.status)}</span><p class="card-excerpt">${esc(s.description)}</p></div></article>`).join('');$$('.artifact-card').forEach(c=>{c.onclick=()=>openRecord(c.dataset.id);c.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openRecord(c.dataset.id)}}})}
  function openRecord(id){const s=stories.find(x=>x.id===id);if(!s)return;current=s;$('#recordAccession').textContent='ACCESSION '+s.id;$('#recordTitle').textContent=s.title;$('#recordText').textContent=s.text||s.description;$('#recordDescription').textContent=s.description;$('#recordNote').textContent=s.note||'The circumstances were not documented';$('#recordContributor').textContent='Contributor: '+(s.username||'Anonymous');$('#recordMeta').innerHTML=`<div><span>Category</span><strong>${esc(s.category)}</strong></div><div><span>Started</span><strong>${esc(s.year)}</strong></div><div><span>Status</span><strong>${esc(s.status)}</strong></div><div><span>Accession</span><strong>${esc(s.id)}</strong></div>`;open('#recordModal')}
  function share(){if(!current)return;$('#shareCardTitle').textContent=current.title;$('#shareCardAccession').textContent=current.id;$('#shareCardUser').textContent=current.username||'Anonymous';open('#shareModal')}
  function shareDo(type){if(!current)return;const url=`${location.origin}${location.pathname}#record=${encodeURIComponent(current.id)}`,text=`${current.title} — ${current.id}\nThe Museum of Unfinished Things`;if(type==='copy'){navigator.clipboard?.writeText(url).then(()=>toast('Link copied')).catch(()=>{const x=document.createElement('textarea');x.value=url;document.body.append(x);x.select();document.execCommand('copy');x.remove();toast('Link copied')});return}if(type==='whatsapp')window.open(`https://wa.me/?text=${encodeURIComponent(text+'\n'+url)}`,'_blank','noopener');if(type==='x')window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`,'_blank','noopener');if(type==='instagram'){navigator.clipboard?.writeText(url);window.open('https://www.instagram.com/','_blank','noopener');toast('Link copied — Instagram opened')}}
  function updateClock(){const d=new Date(),p=n=>String(n).padStart(2,'0'),ms=String(d.getMilliseconds()).padStart(3,'0'),months=['JANUARY','FEBRUARY','MARCH','APRIL','MAY','JUNE','JULY','AUGUST','SEPTEMBER','OCTOBER','NOVEMBER','DECEMBER'];$('#clockTime').textContent=`${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}.${ms}`;$('#clockDate').textContent=`${p(d.getDate())} ${months[d.getMonth()]} ${d.getFullYear()}`}
  function theme(){const b=localStorage.getItem('mout-theme')==='black';document.body.classList.toggle('black-mode',b);$('#themeToggle').textContent=b?'Light mode':'Black mode'}
  function readAvatar(file,done){if(!file)return done('');const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const c=document.createElement('canvas'),m=240,s=Math.min(1,m/Math.max(img.width,img.height));c.width=Math.round(img.width*s);c.height=Math.round(img.height*s);c.getContext('2d').drawImage(img,0,0,c.width,c.height);done(c.toDataURL('image/jpeg',.78))};img.src=r.result};r.readAsDataURL(file)}
  function resetSubmit(){const f=$('#submitForm');f.reset();$('#receipt').hidden=true;f.hidden=false;$('#submitStatus').textContent=''}
  async function currentUser(){return supa?(await supa.auth.getUser()).data.user:null}
  async function account(){open('#accountModal');await renderAccount()}
  async function renderAccount(){const c=$('#accountContent'),u=await currentUser();if(adminToken){renderDesk();return}if(!u){c.innerHTML=`<div class="account-choice"><button class="active" id="loginTab"><span class="eyebrow">Returning contributor</span><strong>Sign in</strong><small>Return to your records</small></button><button id="signupTab"><span class="eyebrow">New contributor</span><strong>Create identity</strong><small>Username, password and optional picture</small></button></div><div id="accountFormArea"></div>`;showAccountForm('login');$('#loginTab').onclick=()=>{showAccountForm('login');$('#loginTab').classList.add('active');$('#signupTab').classList.remove('active')};$('#signupTab').onclick=()=>{showAccountForm('signup');$('#signupTab').classList.add('active');$('#loginTab').classList.remove('active')};return}const p=(await supa.from('profiles').select('username,avatar_data').eq('id',u.id).maybeSingle()).data||{};const mine=(await supa.from('artifacts').select('accession,title,status').eq('owner_id',u.id).order('created_at',{ascending:false})).data||[];c.innerHTML=`<div class="identity-head"><div class="identity-avatar">${p.avatar_data?`<img src="${esc(p.avatar_data)}" alt="">`:esc((p.username||'C')[0].toUpperCase())}</div><div><span class="eyebrow">Archive identity</span><div class="receipt-number" style="font-size:2.8rem">${esc(p.username||'contributor')}</div></div></div><p class="modal-intro">Your identity only helps you return to your own records. Published stories remain public</p><div class="record-section"><span class="eyebrow">Your records</span><div class="account-list">${mine.length?mine.map(a=>`<div class="account-list-row"><div><strong>${esc(a.accession)}</strong> — ${esc(a.title)}<br><small>${esc(a.status)}</small></div></div>`).join(''):'<p>No records yet</p>'}</div></div><div class="account-actions"><button class="button button-dark" id="accountLeave">Leave a record ↗</button><button class="button button-outline" id="logout">Sign out</button></div>`;$('#logout').onclick=async()=>{await supa.auth.signOut();renderAccount()};$('#accountLeave').onclick=()=>{close();resetSubmit();open('#submitModal')}}
  function showAccountForm(mode){const a=$('#accountFormArea');if(mode==='login')a.innerHTML=`<form id="accountForm"><p class="form-explainer">Use the username and password you created</p><label>Username<input name="username" required pattern="[A-Za-z0-9_]{3,24}" autocomplete="username"></label><label>Password<input name="password" type="password" required autocomplete="current-password"></label><button class="button button-dark">Sign in ↗</button><p id="accountMsg" class="form-status"></p></form>`;else a.innerHTML=`<form id="accountForm"><p class="form-explainer">Just a username and password. The picture is optional</p><label>Username<input name="username" required pattern="[A-Za-z0-9_]{3,24}" autocomplete="username"></label><label>Password<input name="password" type="password" minlength="8" required autocomplete="new-password"></label><label>Profile picture <span class="optional">optional</span><input id="identityAvatar" type="file" accept="image/*"></label><div id="identityAvatarPreview" class="avatar-preview" hidden></div><button class="button button-dark">Create identity ↗</button><p id="accountMsg" class="form-status"></p></form>`;$('#accountForm').dataset.mode=mode;$('#accountForm').onsubmit=authForm;if(mode==='signup')$('#identityAvatar').onchange=e=>readAvatar(e.target.files[0],d=>{window._avatar=d;$('#identityAvatarPreview').hidden=!d;$('#identityAvatarPreview').innerHTML=d?`<img src="${esc(d)}" alt="Preview">`:''})}
  async function authForm(e){e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get('username')).trim(),pass=String(f.get('password')),msg=$('#accountMsg'),signup=e.currentTarget.dataset.mode==='signup';if(!/^[A-Za-z0-9_]{3,24}$/.test(name)){msg.textContent='Use 3–24 letters, numbers or underscores';return}if(name.toLowerCase()==='404existential'){if(!signup){const r=await fetch(CONTROL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'admin-login',username:name,password:pass})}).then(x=>x.json());if(!r.token){msg.textContent=r.error||'Sign in failed';return}adminToken=r.token;sessionStorage.setItem('mout-admin-token',adminToken);renderDesk();return}msg.textContent='That username is reserved';return}if(!supa){msg.textContent='Account service unavailable';return}if(signup){const r=await fetch(CONTROL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'register',username:name,password:pass,avatar_data:window._avatar||null})}).then(x=>x.json());if(r.error){msg.textContent=r.error;return}}const r=await supa.auth.signInWithPassword({email:name.toLowerCase()+'@mout.local',password:pass});if(r.error){msg.textContent=r.error.message;return}window._avatar='';await renderAccount()}
  async function submitStory(e){e.preventDefault();const f=new FormData(e.currentTarget),anonymous=f.get('anonymous')==='on',u=await currentUser(),title=String(f.get('title')).trim(),category=String(f.get('category')),year=String(f.get('year')||new Date().getFullYear()),text=String(f.get('text')).trim(),reason=String(f.get('reason')||'').trim(),username=anonymous?'Anonymous':String(f.get('username')||'Anonymous').trim()||'Anonymous',status=$('#submitStatus');if(!title||!category||!text){status.textContent='Please add a title, category and story';return}const story={id:'A—'+String(Date.now()).slice(-7),title,category,year,status:'Published',visual:['red','blue','green','yellow','paper','dark'][Math.floor(Math.random()*6)],description:reason||'A record submitted to the public collection',text,note:reason,username};const row={accession:story.id,title,category,year,status:'Published',reason,visual:story.visual,description:story.description,record_text:text,contributor_note:reason,contributor_username:username,owner_id:u?.id||null};if(supa){const r=await supa.from('artifacts').insert(row);if(r.error){status.textContent=r.error.message;return}}else{const local=JSON.parse(localStorage.getItem('mout-local-stories')||'[]');local.unshift(story);localStorage.setItem('mout-local-stories',JSON.stringify(local))}stories=[story,...stories.filter(s=>s.id!==story.id)];render();$('#receiptNumber').textContent=story.id;e.currentTarget.hidden=true;$('#receipt').hidden=false}
  async function load(){try{const local=JSON.parse(localStorage.getItem('mout-local-stories')||'[]');stories=[...local,...stories]}catch{}if(supa){const r=await supa.from('artifacts').select('accession,title,category,year,status,reason,visual,description,contributor_note,contributor_username,record_text').eq('status','Published').order('created_at',{ascending:false});if(r.data){const ids=new Set(r.data.map(x=>x.accession));stories=[...r.data.map(a=>({id:a.accession,title:a.title,category:a.category,year:a.year||'2026',status:a.status||'Unattended',visual:a.visual||'paper',description:a.description||'',text:a.record_text||'',note:a.reason||a.contributor_note||'',username:a.contributor_username||'Anonymous'})),...stories.filter(x=>!ids.has(x.id))]}}render()}
  async function adminFetch(action,data={}){const r=await fetch(CONTROL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,token:adminToken,...data})});const j=await r.json();if(r.status===401){adminToken='';sessionStorage.removeItem('mout-admin-token');toast('Collection desk session ended');renderAccount();return null}if(j.error){toast(j.error);return null}return j}
  async function renderDesk(){const c=$('#accountContent'),r=await adminFetch('list');if(!r)return;c.innerHTML=`<div class="identity-head"><div class="identity-avatar">404</div><div><span class="eyebrow">Collection desk</span><div class="receipt-number" style="font-size:2.4rem">${r.data.length} records</div></div></div><p class="modal-intro">Edit, publish, withdraw or remove any public record</p><div class="desk-list">${r.data.map(a=>`<details class="desk-item"><summary><strong>${esc(a.accession)}</strong> — ${esc(a.title)} <span>${esc(a.status)}</span></summary><form class="desk-form" data-id="${esc(a.accession)}"><label>Title<input name="title" value="${esc(a.title)}"></label><label>Category<input name="category" value="${esc(a.category)}"></label><label>Year<input name="year" value="${esc(a.year||'2026')}"></label><label>Status<select name="status"><option ${a.status==='Published'?'selected':''}>Published</option><option ${a.status==='Withdrawn'?'selected':''}>Withdrawn</option></select></label><label>Description<textarea name="description" rows="3">${esc(a.description||'')}</textarea></label><label>Story<textarea name="record_text" rows="8">${esc(a.record_text||'')}</textarea></label><label>Why it stopped<textarea name="reason" rows="3">${esc(a.reason||'')}</textarea></label><label>Contributor<input name="contributor_username" value="${esc(a.contributor_username||'Anonymous')}"></label><div class="account-actions"><button class="button button-dark" type="submit">Save changes</button><button class="button button-outline" type="button" data-delete="${esc(a.accession)}">Delete</button></div><p class="form-status"></p></form></details>`).join('')}</div><button class="button button-outline" id="deskLogout">Leave collection desk</button>`;$$('.desk-form').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(f));const r=await adminFetch('update',{accession:f.dataset.id,...d});if(r){f.querySelector('.form-status').textContent='Saved';await load();}});$$('.desk-form [data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this record permanently?'))return;const r=await adminFetch('delete',{accession:b.dataset.delete});if(r){await load();await renderDesk()}});$('#deskLogout').onclick=()=>{adminToken='';sessionStorage.removeItem('mout-admin-token');renderAccount()}}
  $('#themeToggle').onclick=()=>{const b=!document.body.classList.contains('black-mode');document.body.classList.toggle('black-mode',b);localStorage.setItem('mout-theme',b?'black':'light');theme()};
  $('#menuButton').onclick=()=>$('#mainNav').classList.toggle('mobile-open');$$('#mainNav a').forEach(a=>a.onclick=()=>$('#mainNav').classList.remove('mobile-open'));
  $('#accountButton').onclick=account;$('#floatingPost').onclick=()=>{resetSubmit();open('#submitModal')};$('#searchInput').oninput=render;$('#clearFilters').onclick=()=>{$('#searchInput').value='';filter='All';buildFilters();render()};
  $$('[data-close-modal]').forEach(b=>b.onclick=close);$$('.modal-backdrop').forEach(m=>m.onclick=e=>{if(e.target===m)close()});document.onkeydown=e=>{if(e.key==='Escape')close()};$('#shareTrigger').onclick=share;$('#recordShareBottom').onclick=share;$$('.share-actions button').forEach(b=>b.onclick=()=>shareDo(b.dataset.share));
  $('#submitForm').querySelector('select').innerHTML='<option value="">Select</option>'+categories.map(c=>`<option>${c}</option>`).join('');$('#submitForm').onsubmit=submitStory;$$('.exhibition-card button').forEach(b=>b.onclick=()=>{filter=b.dataset.exhibition;buildFilters();render();$('#collection').scrollIntoView({behavior:'smooth'})});
  theme();buildFilters();render();updateClock();setInterval(updateClock,100);load();
  const hash=decodeURIComponent(location.hash);if(hash.startsWith('#record='))setTimeout(()=>openRecord(hash.slice(8)),300);
})();
