-- Museum of Unfinished Things — current database schema
-- Username-only identities intentionally use a synthetic auth email internally.
-- In Supabase Auth, turn OFF Confirm email for the intended username/password flow.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  avatar_data text,
  created_at timestamptz not null default now()
);

create table if not exists public.artifacts (
  id bigint generated by default as identity primary key,
  accession text not null unique,
  title text not null,
  category text not null,
  year text,
  status text not null default 'Published',
  reason text,
  visual text not null default 'paper',
  description text not null,
  contributor_note text,
  record_text text,
  contributor_username text not null default 'Anonymous',
  owner_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists artifacts_category_idx on public.artifacts(category);
create index if not exists artifacts_owner_idx on public.artifacts(owner_id);
create index if not exists artifacts_created_idx on public.artifacts(created_at desc);
create unique index if not exists profiles_username_lower_uidx on public.profiles(lower(username));

alter table public.profiles enable row level security;
alter table public.artifacts enable row level security;

drop policy if exists "public can read profiles" on public.profiles;
create policy "public can read profiles" on public.profiles for select using (true);

drop policy if exists "users can create own profile" on public.profiles;
create policy "users can create own profile" on public.profiles for insert with check (auth.uid() = id);

drop policy if exists "users can update own profile" on public.profiles;
create policy "users can update own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "public can read published artifacts" on public.artifacts;
create policy "public can read published artifacts" on public.artifacts for select using (status = 'Published' or owner_id = auth.uid());

drop policy if exists "authenticated users can publish artifacts" on public.artifacts;
create policy "authenticated users can publish artifacts" on public.artifacts for insert to authenticated with check (owner_id = auth.uid());

drop policy if exists "owners can update own artifacts" on public.artifacts;
create policy "owners can update own artifacts" on public.artifacts for update using (owner_id = auth.uid()) with check (owner_id = auth.uid());

drop policy if exists "owners can delete own artifacts" on public.artifacts;
create policy "owners can delete own artifacts" on public.artifacts for delete using (owner_id = auth.uid());

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (new.id, coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
